# Generated by Django 6.0.5 on 2026-05-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('current_turn', models.PositiveIntegerField(default=1)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('seed', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=20)),
                ('food', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('production', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nations', to='hexquest.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('unit_type', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('settler', 'Settler')], max_length=20)),
                ('strength', models.IntegerField(default=10)),
                ('movement', models.IntegerField(default=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='hexquest.game')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='hexquest.nation')),
            ],
        ),
        migrations.CreateModel(
            name='HexTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('terrain', models.CharField(choices=[('water', 'Water'), ('plains', 'Plains'), ('forest', 'Forest'), ('hill', 'Hill'), ('mountain', 'Mountain'), ('desert', 'Desert')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hexes', to='hexquest.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hexes', to='hexquest.nation')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'q', 'r'], name='hexquest_he_game_id_0d7c8c_idx'), models.Index(fields=['game', 'owner'], name='hexquest_he_game_id_04ca3a_idx')],
                'unique_together': {('game', 'q', 'r')},
            },
        ),
    ]
