# Generated by Django 6.0.5 on 2026-05-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0004_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_timer',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='nation',
            name='has_ended_turn',
            field=models.BooleanField(default=False),
        ),
    ]
