# Generated by Django 6.0.5 on 2026-05-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0005_game_turn_end_time_game_turn_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starting_food',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_gold',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_settlers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
