# Generated by Django 6.0.5 on 2026-05-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0006_game_starting_food_game_starting_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='hexquest.game')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='hexquest.nation')),
            ],
            options={
                'unique_together': {('game', 'q', 'r')},
            },
        ),
    ]
