# Generated by Django 6.0.5 on 2026-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0007_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='population',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tier',
            field=models.CharField(choices=[('village', 'Village'), ('town', 'Town'), ('city', 'City')], default='village', max_length=20),
        ),
    ]
