# Generated by Django 6.0.5 on 2026-05-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0008_settlement_population_settlement_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='hextile',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hexes', to='hexquest.settlement'),
        ),
    ]
