# Generated by Django 6.0.5 on 2026-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0009_hextile_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='last_action_turn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_action_turn',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
