# Generated by Django 6.0.5 on 2026-05-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0010_settlement_last_action_turn_unit_last_action_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='queued_action',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='queued_action',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
