# Generated by Django 6.0.5 on 2026-05-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0011_settlement_queued_action_unit_queued_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='last_activity_turn',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
