# Generated by Django 6.0.5 on 2026-05-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0012_game_is_finished_game_last_activity_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_abandoned',
            field=models.BooleanField(default=False),
        ),
    ]
