# Generated by Django 6.0.5 on 2026-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0013_game_is_abandoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='settlement_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nation',
            name='unit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
