# Generated by Django 6.0.5 on 2026-08-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0015_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('settler', 'Settler'), ('builder', 'Builder')], max_length=20),
        ),
    ]
