# Generated by Django 6.0.5 on 2026-08-05 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0016_alter_unit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('wheat_farm', 'Wheat Farm')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='hexquest.game')),
                ('hex_tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='hexquest.hextile')),
            ],
        ),
    ]
