# Generated by Django 6.0.5 on 2026-08-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0017_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hexquest.nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='round_activity_occurred',
            field=models.BooleanField(default=False),
        ),
    ]
