# Generated by Django 6.0.5 on 2026-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexquest', '0018_game_active_nation_game_round_activity_occurred'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='queued_action',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='hitpoints',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('wheat_farm', 'Wheat Farm'), ('barracks', 'Barracks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('settler', 'Settler'), ('builder', 'Builder'), ('spearman', 'Spearman'), ('swordsman', 'Swordsman')], max_length=20),
        ),
    ]
